superlists/lists/urls.py
from django.conf.urls import url
from lists.views import view_list, new_list

urlpatterns = [
    url(r'^(\d+)/$',view_list, name='view_list'),
    url(r'^new$', new_list, name='new_list')
    
]

superlists/superlists/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from lists.views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^lists/',include('lists.urls')),
    url(r'^$',home_page,name='home'),
]

superlists/lists/models.py
from typing import Text
from django.db import models
from django.db.models.deletion import CASCADE
from django.urls import reverse

# Create your models here.
class List(models.Model):
  
  def get_absolute_url(self):
      return reverse("view_list", args=[self.id])

class Item(models.Model):
  text = models.TextField(default='')
  list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

  def __str__(self):
    return self.text
  
  class Meta:
    ordering = ('id',)
    unique_together = ('list','text')

  
  

superlists/lists/forms.py
from django import forms
from lists.models import Item

EMPTY_LIST_ERROR = "Element listy nie może być pusty"
DUPLICATE_ITEM_ERROR = "Podany element już istnieje na liście"

class ItemForm(forms.models.ModelForm):

  def save(self, for_list):
      self.instance.list = for_list
      return super().save()

  class Meta:
    model = Item
    fields = ('text',)
    widgets = {
      'text': forms.fields.TextInput( attrs = {
        'placeholder': 'Wpisz rzeczy do zrobienia',
        'class': 'form-control input-lg'
      }),
    }
    error_messages = {
      'text': {'required': EMPTY_LIST_ERROR}
    }

    

superlists/lists/views.py
from django.shortcuts import redirect, render
from lists.forms import ItemForm, EMPTY_LIST_ERROR
from django.views.decorators.csrf import csrf_exempt
from lists.models import Item, List
from django.core.exceptions import ValidationError

# Create your views here.

@csrf_exempt
def home_page(request):
  return render(request, 'home.html', {'form': ItemForm()})

@csrf_exempt
def view_list(request, list_id):
  list_ = List.objects.get(id=list_id)
  form = ItemForm()
  if request.method == 'POST':
    form = ItemForm(data=request.POST)
    if form.is_valid():
      Item.objects.create(text=request.POST['text'], list = list_)
      return redirect(list_)
  return render(request, 'list.html',{'list':list_,"form":form})

@csrf_exempt
def new_list(request):
  error = EMPTY_LIST_ERROR
  form = ItemForm(data=request.POST)
  if form.is_valid():
    list_ = List.objects.create()
    Item.objects.create(text = request.POST['text'], list=list_)
    return redirect(list_)
  else:
    return render(request, 'home.html',{"form":form,"error": error})

superlists/lists/templates/base.html
<!DOCTYPE html>
<html lang="pl">

<html>
  <head>
    <title>Listy rzeczy do zrobienia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/base.css" rel="stylesheet" media="screen">
  </head>
  <body>
  <div class="container">

    <div class="row">
      <div class="col-md-6 col-md-offset-3 jumbotron">
        <div class="text-center">
          <h1>{% block header_text%} {% endblock %}</h1>
          <form method="POST" action=" {% block form_action %}{% endblock  %}">
            {{ form.text }}
            {% if error %}
              <div class="form-group has-error">
                <span class="help-block">{{form.text.errors}}</span>
              </div>
            {% endif %}
          </form>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        {% block table %}
        {% endblock  %}
      </div>
    </div>
  </div>
  </body>
</html>

superlists/lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Utwórz nową listę rzeczy do zrobienia{% endblock  %}

{% block form_action %}{% url 'new_list' %}{% endblock  %}

superlists/lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Twoja lista rzeczy do zrobienia{% endblock  %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock  %}

{% block table %}
  <table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
      <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
    {% endfor %}
  </table>
{% endblock  %}